# Generated by Django 4.2.1 on 2023-05-24 01:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tweet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tweet_url", models.URLField()),
                ("author_name", models.CharField(max_length=255)),
                ("author_url", models.URLField()),
                ("tweet_content", models.TextField()),
                ("sentiment", models.JSONField(default=dict)),
                (
                    "analyzed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
    ]
