# Generated by Django 4.2.1 on 2023-05-24 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("twitter", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tweet",
            name="tweet_status",
            field=models.CharField(default="None", max_length=50),
        ),
    ]
