# Generated by Django 4.2.1 on 2023-05-21 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RedditPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("post_id", models.CharField(max_length=10)),
                ("title", models.CharField(max_length=300)),
                ("author", models.CharField(max_length=100)),
                ("submission_date", models.DateTimeField()),
                ("score", models.IntegerField()),
                ("num_comments", models.IntegerField()),
                ("num_top_level_comments", models.IntegerField()),
                ("body", models.TextField()),
                ("subreddit", models.CharField(max_length=100)),
                ("thumbnail", models.URLField()),
                ("permalink", models.URLField()),
                ("sentiment", models.JSONField(null=True)),
            ],
        ),
    ]
